# This is a config for E2B sandbox template.
# You can use template ID (b6ntzryq8pxra44trhnp) or template name (helohelohelo2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("helohelohelo2") # Sync sandbox
# sandbox = await AsyncSandbox.create("helohelohelo2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('helohelohelo2')

team_id = "80cbb72e-e79f-4ecc-a291-466166490b28"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "helohelohelo2"
template_id = "b6ntzryq8pxra44trhnp"
